#!/bin/sh

echo "change ${ACTION}" > /dev/console
if [ "${ACTION}" = "pressed" -a "$BUTTON" = "reset" ]; then

echo $ACTION > /tmp/sysinfo/button_state
/bin/button_light &

elif [ "${ACTION}" = "released" -a "$BUTTON" = "reset" ]; then
kill -9 $(pidof button_light)

echo $ACTION > /tmp/sysinfo/button_state

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

board_name=$(cat /tmp/sysinfo/board_name)

if [ "$SEEN" -lt 1 -a "$BUTTON" = "reset" ]
then
	case "$board_name" in
	cf-e500n | \
	cf-e510n | \
	cf-wr800n | \
	cf-n1)
		echo "WPS Start" > /dev/console
		wps start
	;;
	cf-wr752acv2 | \
	cf-wr753ac | \
	cf-wr755ac | \
	cf-wr758ac | \
	cf-ac1200 | \
	jw-wr758ac | \
	jw-wr768ac)
		echo "MTK WPS 2G Start" > /dev/console
		mtk_wps start 2
	;;
	cf-wr754ac)
		echo "no something to do" > /dev/console
	;;
	*)
		echo "REBOOT" > /dev/console
		sync
		reboot
	;;
	esac

elif [ "$SEEN" -lt 5 ]
then
	kill -9 $(pidof button_light)
	case "$board_name" in
	cf-e500n | \
	cf-e510n | \
	cf-wr800n |\
	cf-n1)
		echo "WPS Start" > /dev/console
		wps start
	;;
	cf-wr752acv2 | \
	cf-wr753ac | \
	cf-wr755ac | \
	cf-wr758ac | \
	cf-ac1200 | \
	jw-wr758ac | \
	jw-wr768ac)
		echo "MTK WPS 5G Start" > /dev/console
		mtk_wps start 5
	;;
	cf-wr754ac)
		echo "no something to do" > /dev/console
	;;
	*)
		echo "REBOOT" > /dev/console
		sync
		reboot
	;;
	esac

elif [ "$SEEN" -ge 5 ]
then
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
fi
fi
