#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1

FOTA_INTERVAL=21600  # 6 hours

start_service() {
    local enabled
    enabled=$(uci -q get system.@system[0].auto_upgrade)
    [ "$enabled" = "1" ] || return 0

    procd_open_instance
    procd_set_param command /bin/sh -c "while true; do /usr/bin/fota_git -w; sleep $FOTA_INTERVAL; done"
    procd_set_param respawn
    procd_close_instance
}
