#!/bin/sh /etc/rc.common

START=97
STOP=98

USE_PROCD=1

start_service() {
	heart_beat_enable=`uci get system.heart_beat.hb_enable`
	if [ "$heart_beat_enable"x == "0"x ]; then
		echo "------------heart_beat------------------" > /dev/console
		killall heart_beat
		return 0;
	fi
	procd_open_instance
	procd_set_param command /usr/bin/heart_beat
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	killall heart_beat
}

stop_service() {
	killall heart_beat
}

service_running() {
	sleep 1
}

service_triggers()
{
	procd_add_reload_trigger "heart_beat"
}

restart() {
	sleep 1
	trap '' TERM
	stop "$@"
	start "$@"
}

shutdown() {
	stop
}
