#!/bin/sh /etc/rc.common
# wbsrv - lightweight HTTP server replacing nginx

START=80

USE_PROCD=1

start_service() {
	[ -d /var/etc ] || mkdir -p /var/etc

	procd_open_instance
	procd_set_param command /usr/sbin/wbsrv -p 80 -r /www-comfast -f 127.0.0.1:9002
	procd_set_param respawn
	procd_close_instance
}
